### ISSUE TITLE
actively update, modern ruby implementation

### ISSUE THREAD

**Issue by kerben** [freenet/lib-rubyFreenet#1]
https://github.com/kerben/ruby-fcp
I actively update it and it uses somewhat similar techniques, in gem format and available on ruby gems as well. If you are interested.
I could update the programs within this to work with my module as well if that would make a difference.

**Comment by Thynix** [comment]
I've added a link on the [wiki](https://wiki.freenetproject.org/FCPv2#Library_Implementations).
